services:
  api:
    build:
      context: ./
      dockerfile: apps/api/Dockerfile
    ports:
      - '4202:4202' # dockerized api runs on localhost:4202 while host api runs on localhost:4201
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379 # api will connect to redis on redis:6379 in the same network
    volumes:
      - .:/app
      - /app/node_modules

  redis:
    image: redis:alpine
    ports:
      - '6389:6379' # don't conflict with redis on host machine running on 6379
